### ISSUE TITLE
Unplash API not viable

### ISSUE THREAD

**Issue by renttrent** [renttrent/firefox-new-page#1]
Unsplash API freezes requests frequently. Looking for other options to fetch random images open to suggestions.

**Comment by blaw6331** [comment]
I believe your issue is that the Unsplash API rate limits you at 50 requests per hour see: https://unsplash.com/documentation#rate-limiting
Ironically if you make an unauthenticated request to https://source.unsplash.com/random then there is not really a rate limit 
If you make a request within around 5 seconds as your last then it will just return the same image but I've tested it with well over 100 tabs and it still works 

approve my pull request here: https://github.com/renttrent/firefox-new-page/pull/2

**Comment by renttrent** [comment]
Haha well that's pretty funny. Thanks for the PR.
